repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format --check
        language: system
        types: [file, python]
      - id: ruff-lint
        name: ruff-lint
        entry: uv run ruff check
        language: system
        types: [file, python]
      - id: mypy
        name: mypy
        description: ""
        entry: uv run mypy
        language: python
        "types_or": [python, pyi]
      - id: pytest
        name: pytest
        description: ""
        entry: uv run pytest test/unit
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
